{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authenticationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/axpcore\/axperror\/authenticationfailed(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"If the request could not be authenticated"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/authenticationFailed(_:)"},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"modules":[{"name":"AXPCore"}],"title":"AXPError.authenticationFailed(_:)","symbolKind":"case","externalID":"s:7AXPCore8AXPErrorO20authenticationFailedyACs5Error_pcACmF","role":"symbol","roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"references":{"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore":{"title":"AXPCore","kind":"symbol","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","abstract":[{"text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user.","type":"text"}],"url":"\/documentation\/axpcore","role":"collection","type":"topic"},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError/authenticationFailed(_:)":{"title":"AXPError.authenticationFailed(_:)","type":"topic","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/authenticationFailed(_:)","abstract":[{"type":"text","text":"If the request could not be authenticated"}],"kind":"symbol","role":"symbol","url":"\/documentation\/axpcore\/axperror\/authenticationfailed(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError":{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol","title":"AXPError","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPError","kind":"identifier"}],"navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"text":" ","type":"text"},{"text":"across the network.","type":"text"}]}}}