{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/axpcore\/axperror\/authenticationfailed(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError\/authenticationFailed(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If the request could not be authenticated"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"AXPError.authenticationFailed(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:7AXPCore8AXPErrorO20authenticationFailedyACs5Error_pcACmF","modules":[{"name":"AXPCore"}]},"hierarchy":{"paths":[["doc:\/\/AXPCore\/documentation\/AXPCore","doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError"]]},"references":{"doc://AXPCore/documentation/AXPCore":{"role":"collection","title":"AXPCore","abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore","kind":"symbol","type":"topic","url":"\/documentation\/axpcore"},"doc://AXPCore/documentation/AXPCore/AXPError/authenticationFailed(_:)":{"role":"symbol","title":"AXPError.authenticationFailed(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"If the request could not be authenticated"}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError\/authenticationFailed(_:)","kind":"symbol","type":"topic","url":"\/documentation\/axpcore\/axperror\/authenticationfailed(_:)"},"doc://AXPCore/documentation/AXPCore/AXPError":{"role":"symbol","title":"AXPError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXPError"}],"abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"type":"text","text":"across the network."}],"identifier":"doc:\/\/AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AXPError"}],"url":"\/documentation\/axpcore\/axperror"}}}